<a href="https://colab.research.google.com/github/VaibhaviDeveloper/MSIS_AML/blob/main/GroceriesAML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
os.listdir('/content/drive/MyDrive')

['Kaagaz_20220914_141308009993.pdf',
 'Kaagaz_20220914_141308009993.gdoc',
 'Untitled presentation (4).gslides',
 'Untitled presentation (3).gslides',
 'Untitled presentation (2).gslides',
 'Untitled presentation (1).gslides',
 'Untitled presentation.gslides',
 'Untitled form (1).gform',
 'Untitled form.gform',
 'AmazonLogo.jpg',
 'SignIn.jpg',
 'E-Commerce.html',
 'SignUp.html',
 'SignIn.html',
 'Forgot.html',
 'Successful.html',
 'style (1).css',
 'StripLight.jpg',
 'hero-img.jpg',
 'style2.css',
 'Laptop.jpg',
 'Smartwatch.jpg',
 'RoomFreshner.jpg',
 'signup.html',
 'signin.html',
 'forgot.html',
 'twoa.html',
 'styletwo.css',
 'style.css',
 'successfull.html',
 'AmazonImage.jpg',
 'ScrollinBlinking.html',
 "Vaibhavi's Resume.pdf",
 "Vaibhavi's Resume (1).gdoc",
 "Vaibhavi's Resume.gdoc",
 'nnm22cs195.pdf',
 'Vaibhavi N-Resume (3).pdf',
 'Sambhram Permission.gdoc',
 'Vaibhavi N-Resume (1).pdf',
 'Vaibhavi N-Resume.pdf',
 'Classroom',
 'archive (8)',
 'Patent APPLICATION FORM.docx',
 'Final_Year_Project (1).gdoc',
 'Vaibhavi N-Resume (2).pdf',
 'Vaibhavi N-Resume (2)-1.pdf',
 'Photoshoot 25',
 'Intern Information Form.docx',
 'Colab Notebooks',
 '36101.jpg',
 'Miniproject_MSIS_papers.docx',
 'bestsellers with categories.csv',
 'Data.csv',
 'Groceries_dataset.csv',
 'Copy of bestsellers with categories.csv',
 'Iris.csv',
 'diabetes.csv',
 'Social_Network_Ads.csv',
 'adult.csv']

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv('/content/drive/MyDrive/Groceries_dataset.csv')

In [6]:
df.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [7]:
df.dtypes

Member_number       int64
Date               object
itemDescription    object
dtype: object

In [8]:
null_num=df.isnull().sum()
null_num

Member_number      0
Date               0
itemDescription    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(759)

In [10]:
df[df.duplicated()]

       Member_number        Date   itemDescription
5015            2051  11-09-2015       frankfurter
5022            3055  18-08-2015  other vegetables
5044            1994  11-03-2015        whole milk
5055            1682  25-06-2015         pip fruit
5059            4324  05-01-2015           sausage
...              ...         ...               ...
38614           2027  26-02-2014     domestic eggs
38684           2936  07-03-2014        newspapers
38685           2311  13-03-2014        pot plants
38722           3834  18-05-2014       salty snack
38723           1146  23-05-2014            yogurt

[759 rows x 3 columns]

In [11]:
df['Member_number'].duplicated().sum()

np.int64(34867)

In [12]:
df.size

116295

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38765 entries, 0 to 38764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38765 non-null  int64
 1   Date             38765 non-null  object
 2   itemDescription  38765 non-null  object
dtypes: int64(1), object(2)
memory usage: 908.7+ KB

In [14]:
df[df.duplicated(keep=False)].sort_values(
    ["Member_number", "Date", "itemDescription"]
).head(20)

       Member_number        Date   itemDescription
33098           1003  27-02-2014        rolls/buns
37649           1003  27-02-2014        rolls/buns
15099           1005  09-01-2014        rolls/buns
31248           1005  09-01-2014        rolls/buns
7532            1006  14-06-2015       frankfurter
8488            1006  14-06-2015       frankfurter
16100           1008  21-07-2015            yogurt
21210           1008  21-07-2015            yogurt
4769            1026  28-05-2015   root vegetables
20918           1026  28-05-2015   root vegetables
3347            1031  15-10-2015  other vegetables
19496           1031  15-10-2015  other vegetables
8608            1035  24-04-2015            yogurt
19786           1035  24-04-2015            yogurt
29972           1045  12-01-2014            yogurt
37270           1045  12-01-2014            yogurt
33006           1051  26-12-2014     shopping bags
37557           1051  26-12-2014     shopping bags
8090            1052  06-07-2015            yogurt
20687           1052  06-07-2015            yogurt

In [15]:
df.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [16]:
df.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk